-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.16.0
    hooks:
    -   id: yapf
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
<<<<<<< HEAD
        exclude: docs/conf.py
=======
        exclude: docs/*
>>>>>>> 4d71de0126fd2979338192782a55642ad41b2c46
    -   id: check-yaml
    -   id: check-merge-conflict
