language: python
python:
    - '3.6'
install:
    - pip install -r requirements_dev.txt
    - python setup.py install
script:
    - make test
    - make examples
after_success:
    - coveralls
deploy:
  provider: pypi
  user: arkottke
  password:
    secure: XJ68lufBupCicSgg7mnA85+IsXVHgqKOV3ZfUwjruKh4J/5e67XJXfKZs5vx66VL872bjoID/NPZ2TpGlf48MMT4leIokPmO0IZy0B4Ixsar0ABq1z76x3YUvFYLIxWGGyd1wtFDZfJiCYHJoO98I/CT/g2Uphb7Fzux77vYGok=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: arkottke/pysra
