language: python
python:
    - '3.6'
install:
    - pip install -r requirements_dev.txt
    - python setup.py install
script:
    - make test
    - make examples
after_success:
    - coveralls
deploy:
  provider: pypi
  user: arkottke
  password:
    secure: !!binary |
      RW5tRGlPRm5yRzNMa1FzNjV0NWN2SHNiTjc3QnJwdTZ4OVlXNWoyeXNXS3BDcnJCWnNCSmg4V0E5
      WFpoczBnaWxmcXE3MktaODg5OEVnY00rRnBQdk1IVWRmMWdCTWlmMVJpRTFWOWpjMVFVQk8yY1Fk
      VTZlQ0J4elhQTERFM1VHQjFVL1djL0d6M1NQU1cvZmY5QzRzTjJQaU5hM3dzc2IvY05ia2hXa0s4
      PQ==
  on:
    distributions: sdist bdist_wheel
    repo: arkottke/pyrvt
    tags: true
